#! format: off

# IMRPhenomXPHM is the precessing extension of IMRPhenomXHM.  The aligned-spin
# co-precessing modes are generated by PhenomXHM.jl; this file contains only the
# MSA Euler angles and the twist-up described in LALSimIMRPhenomXPHM.c and
# LALSimIMRPhenomX_precession.c.  The default LAL precession version 300 maps to
# version 223, which is the implementation below.  The conversion is pinned to
# the public LALSuite tag lalsuite-v7.26.15 (lalsimulation 6.2.1).

const _XPHM_MTSUN_SI = 4.925490947641267e-6
const _XPHM_MRSUN_GPC = 1476.6250380501247 / 3.0856775814913673e25

mutable struct _XPHMMSA
    data::Dict{Symbol,Any}
end

function Base.getproperty(p::_XPHMMSA, name::Symbol)
    name === :data && return getfield(p, :data)
    return getfield(p, :data)[name]
end

function Base.setproperty!(p::_XPHMMSA, name::Symbol, value)
    name === :data && return setfield!(p, :data, value)
    getfield(p, :data)[name] = value
    return value
end

_xphm_norm(v) = sqrt(sum(abs2, v))

function _xphm_get_pn_beta(p, a, b)
    return p.dotS1L * (a + b * p.qq) + p.dotS2L * (a + b / p.qq)
end

function _xphm_get_pn_sigma(p, a, b)
    return p.inveta * (a * p.dotS1S2 - b * p.dotS1L * p.dotS2L)
end

function _xphm_get_pn_tau(p, a, b)
    return (p.qq * (a * p.S1_norm_2 - b * p.dotS1L^2) +
            (a * p.S2_norm_2 - b * p.dotS2L^2) / p.qq) / p.eta
end

function _xphm_spin_evolution_coefficients(p, LNorm, JNorm)
    JNorm2 = JNorm^2
    LNorm2 = LNorm^2
    J2mL2 = JNorm2 - LNorm2
    J2mL2Sq = J2mL2^2
    q = p.qq

    B = (LNorm2 + p.S1_norm_2) * q + 2 * LNorm * p.Seff - 2 * JNorm2 -
        p.S1_norm_2 - p.S2_norm_2 + (LNorm2 + p.S2_norm_2) / q
    C = J2mL2Sq - 2 * LNorm * p.Seff * J2mL2 -
        2 * ((1 - q) / q) * LNorm2 * (p.S1_norm_2 - q * p.S2_norm_2) +
        4 * p.eta * LNorm2 * p.Seff2 -
        2 * p.delta_qq * (p.S1_norm_2 - p.S2_norm_2) * p.Seff * LNorm +
        2 * ((1 - q) / q) * (q * p.S1_norm_2 - p.S2_norm_2) * JNorm2
    D = ((1 - q) / q) * (p.S2_norm_2 - q * p.S1_norm_2) * J2mL2Sq +
        p.delta_qq^2 * (p.S1_norm_2 - p.S2_norm_2)^2 * LNorm2 / p.eta +
        2 * p.delta_qq * LNorm * p.Seff * (p.S1_norm_2 - p.S2_norm_2) * J2mL2
    return B, C, D
end

function _xphm_roots_msa(p, LNorm, JNorm)
    B, C, D = _xphm_spin_evolution_coefficients(p, LNorm, JNorm)
    B2 = B^2
    pp = C - B2 / 3
    qc = (2 / 27) * B2 * B - B * C / 3 + D
    sqrtarg = sqrt(-pp / 3)
    acosarg = clamp(1.5 * qc / pp / sqrtarg, -1, 1)
    theta = acos(acosarg) / 3

    bad = !isfinite(theta) || !isfinite(sqrtarg) ||
          abs(p.dotS1Ln) == 1 || abs(p.dotS2Ln) == 1 ||
          p.S1_norm_2 == 1 || p.S2_norm_2 == 0
    if bad
        return zero(LNorm), p.S_0_norm_2, p.S_0_norm_2 + 1e-9
    end

    roots = [2 * sqrtarg * cos(theta - 4pi / 3) - B / 3,
             2 * sqrtarg * cos(theta - 2pi / 3) - B / 3,
             2 * sqrtarg * cos(theta) - B / 3]
    imax = argmax(roots)
    imin = argmin(roots)
    imid = 6 - imax - imin
    Spl2 = abs(roots[imax])
    S32 = roots[imin]
    Smi2 = abs(roots[imid])
    return S32, Smi2, Spl2
end

_xphm_jnorm(p, LNorm) = sqrt(LNorm^2 + 2 * LNorm * p.c1_over_eta + p.SAv2)

function _xphm_lnorm_3pn(p, v, LNorm)
    v2 = v^2
    c = p.constants_L
    return LNorm * (1 + v2 * (c[1] + v * c[2] + v2 * (c[3] + v * c[4] + v2 * c[5])))
end

function _xphm_psi(p, v; psi0=p.psi0)
    return psi0 - 0.75 * p.g0 * p.delta_qq * (1 + p.psi1 * v + p.psi2 * v^2) / v^3
end

function _xphm_snorm(p, v)
    m = (p.Smi2 - p.Spl2) / (p.S32 - p.Spl2)
    sn = abs(p.Smi2 - p.Spl2) < 1e-5 ? zero(v) : Elliptic.Jacobi.sn(_xphm_psi(p, v), m)
    return sqrt(p.Spl2 + (p.Smi2 - p.Spl2) * sn^2)
end

function _xphm_phiz_msa(p, v, JNorm)
    LNewt = p.eta / v
    c1 = p.c1
    c12 = c1^2
    log1 = log(abs(c1 + JNorm * p.eta + p.eta * LNewt))
    log2 = log(abs(c1 + JNorm * p.SAv * v + p.SAv2 * v))

    z0 = JNorm * p.inveta4 * (0.5c12 - c1 * p.eta2 / v / 6 -
         p.SAv2 * p.eta2 / 3 - p.eta4 / v^2 / 3) -
         0.5c1 * p.inveta * (c12 * p.inveta4 - p.SAv2 * p.inveta2) * log1
    z1 = -0.5JNorm * p.inveta2 * (c1 + p.eta * LNewt) +
         0.5p.inveta3 * (c12 - p.eta2 * p.SAv2) * log1
    z2 = -JNorm + p.SAv * log2 - c1 * log1 * p.inveta
    z3 = JNorm * v - p.eta * log1 + c1 * log2 * p.invSAv
    z4 = 0.5JNorm * p.invSAv2 * v * (c1 + v * p.SAv2) -
         0.5p.invSAv2 * p.invSAv * (c12 - p.eta2 * p.SAv2) * log2
    z5 = -JNorm * v * (0.5c12 * p.invSAv2^2 - c1 * v * p.invSAv2 / 6 -
         v^2 / 3 - p.eta2 * p.invSAv2 / 3) +
         0.5c1 * p.invSAv2^2 * p.invSAv * (c12 - p.eta2 * p.SAv2) * log2

    ans = z0 * p.Omegaz0_coeff + z1 * p.Omegaz1_coeff +
          z2 * p.Omegaz2_coeff + z3 * p.Omegaz3_coeff +
          z4 * p.Omegaz4_coeff + z5 * p.Omegaz5_coeff + p.phiz_0
    return isfinite(ans) ? ans : zero(ans)
end

function _xphm_zeta_msa(p, v)
    ans = p.eta * (p.Omegazeta0_coeff / v^3 + p.Omegazeta1_coeff / v^2 +
          p.Omegazeta2_coeff / v + p.Omegazeta3_coeff * log(v) +
          p.Omegazeta4_coeff * v + p.Omegazeta5_coeff * v^2) + p.zeta_0
    return isfinite(ans) ? ans : zero(ans)
end

function _xphm_constants_c(p, v, JNorm, Spl2, Smi2)
    J2 = JNorm^2
    c0 = JNorm * 0.75 * (1 - p.Seff * v) * v^2 *
         (p.eta3 + 4p.eta3 * p.Seff * v -
          2p.eta * (J2 - Spl2 + 2(p.S1_norm_2 - p.S2_norm_2) * p.delta_qq) * v^2 -
          4p.eta * p.Seff * (J2 - Spl2) * v^3 + (J2 - Spl2)^2 * v^4 * p.inveta)
    c2 = JNorm * (-1.5p.eta * (Spl2 - Smi2) *
         (1 + 2p.Seff * v - (J2 - Spl2) * v^2 * p.inveta2) *
         (1 - p.Seff * v) * v^4)
    c4 = JNorm * 0.75p.inveta * (Spl2 - Smi2)^2 * (1 - p.Seff * v) * v^6
    return c0, c2, c4
end

function _xphm_constants_d(LNorm, JNorm, Spl, Spl2, Smi2)
    d0 = -(JNorm^2 - (LNorm + Spl)^2) * (JNorm^2 - (LNorm - Spl)^2)
    d2 = -2 * (Spl2 - Smi2) * (JNorm^2 + LNorm^2 - Spl2)
    d4 = -(Spl2 - Smi2)^2
    return d0, d2, d4
end

function _xphm_msa_corrections(p, v, LNorm, JNorm, Spl, Spl2, Smi2, S32)
    c0, c2, c4 = _xphm_constants_c(p, v, JNorm, Spl2, Smi2)
    d0, d2, d4 = _xphm_constants_d(LNorm, JNorm, Spl, Spl2, Smi2)
    sd = sqrt(abs(d2^2 - 4d0 * d4))
    Atheta = 0.5 * (JNorm / LNorm + LNorm / JNorm - Spl2 / (JNorm * LNorm))
    Btheta = 0.5 * (Spl2 - Smi2) / (JNorm * LNorm)
    ncnum = 2 * (d0 + d2 + d4)
    ncden = 2d0 + d2 + sd
    nc = ncnum / ncden
    nd = ncden / (2d0)
    sqnc, sqnd = sqrt(abs(nc)), sqrt(abs(nd))
    psi = _xphm_psi(p, v)
    psidot = -0.75 * v^6 * (1 - v * p.Seff) * p.sqrt_inveta * sqrt(Spl2 - S32)
    tanpsi = tan(psi)
    atanpsi = atan(tanpsi)
    C2den = 2d0 * sd * (d0 + d2 + d4)

    Cterm = abs((c4*d0*((2d0+d2)+sd) - c2*d0*((d2+2d4)-sd) -
             c0*(2d0*d4-(d2+d4)*(d2-sd))) / C2den) *
             (sqnc/(nc-1) * (atanpsi - atan(sqnc*tanpsi))) / psidot
    Dterm = abs((-c4*d0*((2d0+d2)-sd) + c2*d0*((d2+2d4)+sd) -
             c0*(-2d0*d4+(d2+d4)*(d2+sd))) / C2den) *
             (sqnd/(nd-1) * (atanpsi - atan(sqnd*tanpsi))) / psidot
    nc == 1 && (Cterm = zero(Cterm))
    nd == 1 && (Dterm = zero(Dterm))
    phicorr = Cterm + Dterm
    zetacorr = Atheta * phicorr + 2Btheta*d0 * (Cterm/(sd-d2) - Dterm/(sd+d2))
    return isfinite(phicorr) ? phicorr : zero(phicorr),
           isfinite(zetacorr) ? zetacorr : zero(zetacorr)
end

function _xphm_msa_angles(p, v)
    Lnewt = p.eta / v
    Jnewt = _xphm_jnorm(p, Lnewt)
    p.S32, p.Smi2, p.Spl2 = _xphm_roots_msa(p, Lnewt, Jnewt)
    p.Spl = sqrt(p.Spl2)
    Snorm = _xphm_snorm(p, v)
    phiz = _xphm_phiz_msa(p, v, Jnewt)
    zeta = _xphm_zeta_msa(p, v)
    if abs(p.Smi2 - p.Spl2) > 1e-5
        dphiz, dzeta = _xphm_msa_corrections(p, v, Lnewt, Jnewt, p.Spl, p.Spl2, p.Smi2, p.S32)
        phiz += dphiz
        zeta += dzeta
    end
    Lfull = _xphm_lnorm_3pn(p, v, Lnewt)
    Jfull = _xphm_jnorm(p, Lfull)
    cosbeta = clamp(0.5 * (Jfull^2 + Lfull^2 - Snorm^2) / (Lfull * Jfull), -1, 1)
    return phiz, zeta, cosbeta
end

function _xphm_initialize_msa(eta, m1, m2, S1v, S2v, Mfref; expansion_order=5)
    p = _XPHMMSA(Dict{Symbol,Any}())
    p.eta = eta
    p.eta2, p.eta3, p.eta4 = eta^2, eta^3, eta^4
    p.inveta, p.inveta2, p.inveta3, p.inveta4 = eta^-1, eta^-2, eta^-3, eta^-4
    p.sqrt_inveta = inv(sqrt(eta))
    p.m1, p.m2, p.Mfref = m1, m2, Mfref

    q = m2 / m1
    p.qq, p.invqq = q, inv(q)
    p.delta_qq = (1 - q) / (1 + q)
    p.delta2_qq, p.delta3_qq, p.delta4_qq = p.delta_qq^2, p.delta_qq^3, p.delta_qq^4
    p.S1_0, p.S2_0 = collect(S1v), collect(S2v)
    p.S1_norm, p.S2_norm = _xphm_norm(S1v), _xphm_norm(S2v)
    p.S1_norm_2, p.S2_norm_2 = p.S1_norm^2, p.S2_norm^2
    p.v_0 = cbrt(pi * Mfref)
    p.v_0_2 = p.v_0^2
    p.L_0 = [zero(eta), zero(eta), eta / p.v_0]
    p.dotS1L, p.dotS2L = S1v[3], S2v[3]
    p.dotS1S2 = sum(S1v .* S2v)
    p.dotS1Ln = p.dotS1L / p.S1_norm
    p.dotS2Ln = p.dotS2L / p.S2_norm

    Lns = [3/2, 1/6, 27/8, -19/8, 1/24, 135/16,
           -6889/144 + 41pi^2/24, 31/24, 7/1296]
    Lso = [-14/6, -3/2, -11/2, 133/72, -33/8, 7/4]
    p.constants_L = [Lns[1] + eta*Lns[2],
                     _xphm_get_pn_beta(p, Lso[1], Lso[2]),
                     Lns[3] + eta*Lns[4] + eta^2*Lns[5],
                     _xphm_get_pn_beta(p, Lso[3] + Lso[4]*eta, Lso[5] + Lso[6]*eta),
                     Lns[6] + Lns[7]*eta + Lns[8]*eta^2 + Lns[9]*eta^3]

    p.Seff = (1 + q) * p.dotS1L + (1 + inv(q)) * p.dotS2L
    p.Seff2 = p.Seff^2
    p.S_0 = S1v + S2v
    p.J_0 = p.L_0 + p.S_0
    p.S_0_norm = _xphm_norm(p.S_0)
    p.S_0_norm_2 = p.S_0_norm^2
    p.L_0_norm = _xphm_norm(p.L_0)
    p.J_0_norm = _xphm_norm(p.J_0)
    p.L_0_norm_2, p.J_0_norm_2 = p.L_0_norm^2, p.J_0_norm^2

    p.S32, p.Smi2, p.Spl2 = _xphm_roots_msa(p, p.L_0_norm, p.J_0_norm)
    p.Spl2pSmi2 = p.Spl2 + p.Smi2
    p.Spl2mSmi2 = p.Spl2 - p.Smi2
    p.Spl, p.Smi = sqrt(p.Spl2), sqrt(p.Smi2)
    p.SAv2 = 0.5 * p.Spl2pSmi2
    p.SAv = sqrt(p.SAv2)
    p.invSAv2, p.invSAv = inv(p.SAv2), inv(p.SAv)
    p.c1 = 0.5 * (p.J_0_norm^2 - p.L_0_norm^2 - p.SAv2) / p.L_0_norm * eta
    p.c1_2 = p.c1^2
    p.c1_over_eta = p.c1 / eta

    omqsq = (1 - q)^2 + 1e-16
    omq2 = 1 - q^2 + 1e-16
    p.S1L_pav = (p.c1*(1+q) - q*eta*p.Seff) / (eta*omq2)
    p.S2L_pav = -q * (p.c1*(1+q) - eta*p.Seff) / (eta*omq2)
    p.S1S2_pav = 0.5p.SAv2 - 0.5(p.S1_norm_2 + p.S2_norm_2)
    p.S1Lsq_pav = p.S1L_pav^2 + p.Spl2mSmi2^2 * p.v_0_2 / (32eta^2*omqsq)
    p.S2Lsq_pav = p.S2L_pav^2 + q^2*p.Spl2mSmi2^2*p.v_0_2/(32eta^2*omqsq)
    p.S1LS2L_pav = p.S1L_pav*p.S2L_pav - q*p.Spl2mSmi2^2*p.v_0_2/(32eta^2*omqsq)

    p.beta3 = (113/12 + 25q/4)*p.S1L_pav + (113/12 + 25/(4q))*p.S2L_pav
    p.beta5 = (31319/1008 - 1159eta/24 + q*(809/84 - 281eta/8))*p.S1L_pav +
              (31319/1008 - 1159eta/24 + inv(q)*(809/84 - 281eta/8))*p.S2L_pav
    p.beta6 = pi*((75/2 + 151q/6)*p.S1L_pav + (75/2 + 151/(6q))*p.S2L_pav)
    b70 = 130325/756 - 796069eta/2016 + 100019eta^2/864
    b71 = 1195759/18144 - 257023eta/1008 + 2903eta^2/32
    # This placement of parentheses intentionally follows LAL exactly.
    p.beta7 = b70 + q*b71*p.S1L_pav + b70 + inv(q)*b71*p.S2L_pav
    mu = m1*m2/(m1+m2)
    p.sigma4 = ((247/48)*p.S1S2_pav - (721/48)*p.S1L_pav*p.S2L_pav)/mu +
               ((233/96)*p.S1_norm_2 - (719/96)*p.S1Lsq_pav)/m1^2 +
               ((233/96)*p.S2_norm_2 - (719/96)*p.S2Lsq_pav)/m2^2

    dns = [96/5, -1486/35, -264/5, 384pi/5, 34103/945, 13661/105,
           944/15, -4159pi/35, -2268pi/5]
    dso = [-904/5, -120, -62638/105, 4636/5, -6472/35, 3372/5]
    dss = [-494/5, -1442/5, -233/5, -719/5]
    p.a0 = eta*dns[1]
    p.a2 = eta*(dns[2] + eta*dns[3])
    p.a3 = eta*(dns[4] + _xphm_get_pn_beta(p, dso[1], dso[2]))
    p.a4 = eta*(dns[5] + eta*(dns[6] + eta*dns[7]) +
           _xphm_get_pn_sigma(p, dss[1], dss[2]) + _xphm_get_pn_tau(p, dss[3], dss[4]))
    p.a5 = eta*(dns[8] + eta*dns[9] +
           _xphm_get_pn_beta(p, dso[3] + eta*dso[4], dso[5] + eta*dso[6]))
    p.a0_2, p.a0_3, p.a2_2 = p.a0^2, p.a0^3, p.a2^2
    p.g0 = inv(p.a0)
    p.g2 = -p.a2/p.a0_2
    p.g3 = -p.a3/p.a0_2
    p.g4 = -(p.a4*p.a0 - p.a2_2)/p.a0_3
    p.g5 = -(p.a5*p.a0 - 2p.a3*p.a2)/p.a0_3

    p.psi0 = 0.0
    p.psi1 = 3 * (2eta^2*p.Seff - p.c1) / (eta*p.delta_qq^2)
    c1nu = p.c1_over_eta
    opq2 = (1+q)^2
    q2 = q^2
    omq22 = (1-q2)^2
    Delta = sqrt(abs((4c1nu^2*opq2 - 8c1nu*q*(1+q)*p.Seff -
            4(omq22*p.S1_norm_2-q2*p.Seff2)) *
           (4c1nu^2*q2*opq2 - 8c1nu*q2*(1+q)*p.Seff -
            4(omq22*p.S2_norm_2-q2*p.Seff2))))
    p.Delta = Delta
    u1 = 3p.g2/p.g0
    u2 = 0.75opq2/(1-q)^4
    u3 = -20c1nu^2*q2*opq2
    u4 = 2omq22*(q*(2+q)*p.S1_norm_2 + (1+2q)*p.S2_norm_2 - 2q*p.SAv2)
    u5 = 4q2*(7+6q+7q2)*c1nu*p.Seff
    u6 = 2q2*(3+4q+3q2)*p.Seff2
    p.psi2 = u1 + u2*(u3+u4+u5-u6+q*Delta)

    Rm = p.Spl2-p.Smi2
    cp = p.Spl2*eta^2-p.c1^2
    cm = p.Smi2*eta^2-p.c1^2
    scp = sqrt(abs(cp*cm))
    D2RmSq = (cp-scp)/eta^2
    D4RmSq = -0.5Rm*scp/eta^2 - cp/eta^4*(scp-cp)
    aw = -3(1+q)/q*(2(1+q)*eta^2*p.Seff*p.c1 - (1+q)*p.c1^2 +
         (1-q)*eta^2*(p.S1_norm_2-p.S2_norm_2))
    cw = 3Rm^2/(32eta)
    dw = 4cp-4D2RmSq*eta^2
    hw = -2(2D2RmSq-Rm)*p.c1
    fw = Rm*D2RmSq-D4RmSq-0.25Rm^2
    adD, hdD, cdD, fdD = aw/dw, hw/dw, cw/dw, fw/dw
    gdD = (3Rm^2*(p.c1-eta^2*p.Seff)/(16eta^3))/dw
    p.Omegaz0 = 0.5 + 0.75/eta + adD
    p.Omegaz1 = -0.75p.Seff/eta - adD*p.Seff - adD*hdD
    p.Omegaz2 = adD*hdD*p.Seff + cdD - adD*fdD + adD*hdD^2
    p.Omegaz3 = (adD*fdD-cdD-adD*hdD^2)*(p.Seff+hdD) + adD*fdD*hdD
    p.Omegaz4 = (cdD+adD*hdD^2-2adD*fdD)*(hdD*p.Seff+hdD^2-fdD)-adD*fdD^2
    p.Omegaz5 = (cdD-adD*fdD+adD*hdD^2)*fdD*(p.Seff+2hdD) -
                (cdD+adD*hdD^2-2adD*fdD)*hdD^2*(p.Seff+hdD)-adD*fdD^2*hdD
    abs(p.Omegaz5) > 1000 && throw(DomainError(p.Omegaz5, "pathological MSA system"))

    p.Omegaz0_coeff = 3p.g0*p.Omegaz0
    p.Omegaz1_coeff = 3p.g0*p.Omegaz1
    p.Omegaz2_coeff = 3(p.g0*p.Omegaz2+p.g2*p.Omegaz0)
    p.Omegaz3_coeff = 3(p.g0*p.Omegaz3+p.g2*p.Omegaz1+p.g3*p.Omegaz0)
    p.Omegaz4_coeff = 3(p.g0*p.Omegaz4+p.g2*p.Omegaz2+p.g3*p.Omegaz1+p.g4*p.Omegaz0)
    p.Omegaz5_coeff = 3(p.g0*p.Omegaz5+p.g2*p.Omegaz3+p.g3*p.Omegaz2+p.g4*p.Omegaz1+p.g5*p.Omegaz0)
    c1eta2 = p.c1/eta^2
    p.Omegazeta0 = p.Omegaz0
    p.Omegazeta1 = p.Omegaz1+p.Omegaz0*c1eta2
    p.Omegazeta2 = p.Omegaz2+p.Omegaz1*c1eta2
    p.Omegazeta3 = p.Omegaz3+p.Omegaz2*c1eta2+gdD
    p.Omegazeta4 = p.Omegaz4+p.Omegaz3*c1eta2-gdD*p.Seff-gdD*hdD
    p.Omegazeta5 = p.Omegaz5+p.Omegaz4*c1eta2+gdD*hdD*p.Seff+gdD*(hdD^2-fdD)
    p.Omegazeta0_coeff = -p.g0*p.Omegazeta0
    p.Omegazeta1_coeff = -1.5p.g0*p.Omegazeta1
    p.Omegazeta2_coeff = -3(p.g0*p.Omegazeta2+p.g2*p.Omegazeta0)
    p.Omegazeta3_coeff = 3(p.g0*p.Omegazeta3+p.g2*p.Omegazeta1+p.g3*p.Omegazeta0)
    p.Omegazeta4_coeff = 3(p.g0*p.Omegazeta4+p.g2*p.Omegazeta2+p.g3*p.Omegazeta1+p.g4*p.Omegazeta0)
    p.Omegazeta5_coeff = 1.5(p.g0*p.Omegazeta5+p.g2*p.Omegazeta3+p.g3*p.Omegazeta2+p.g4*p.Omegazeta1+p.g5*p.Omegazeta0)
    expansion_order in (-1,1,2,3,4,5) || throw(ArgumentError("invalid MSA expansion order"))
    if expansion_order != -1
        # The C switch deliberately falls through: order n retains terms
        # through n-1 and zeros every coefficient from n onward.
        for order in expansion_order:5
            setproperty!(p, Symbol("Omegaz$(order)_coeff"), 0.0)
            setproperty!(p, Symbol("Omegazeta$(order)_coeff"), 0.0)
        end
    end

    if abs(p.Smi2-p.Spl2) < 1e-5
        p.psi0 = 0.0
    else
        mm = (p.Smi2-p.Spl2)/(p.S32-p.Spl2)
        tmpB = (p.S_0_norm_2-p.Spl2)/(p.Smi2-p.Spl2)
        vol = dot(cross(p.L_0, S1v), S2v)
        volsign = copysign(one(vol), vol)
        psi_v0 = _xphm_psi(p, p.v_0; psi0=0.0)
        if 0 <= tmpB <= 1
            p.psi0 = Elliptic.F(asin(volsign*sqrt(tmpB)), mm)-psi_v0
        elseif tmpB > 1 && tmpB-1 < 1e-5
            p.psi0 = Elliptic.F(asin(volsign), mm)-psi_v0
        elseif tmpB < 0 && tmpB > -1e-5
            p.psi0 = -psi_v0
        else
            throw(DomainError(tmpB, "invalid MSA elliptic initial condition"))
        end
    end

    dphi, dzeta = 0.0, 0.0
    if abs(p.Spl2-p.Smi2) > 1e-5
        dphi, dzeta = _xphm_msa_corrections(p, p.v_0, p.L_0_norm, p.J_0_norm,
                                           p.Spl, p.Spl2, p.Smi2, p.S32)
    end
    p.phiz_0 = 0.0
    p.zeta_0 = 0.0
    p.phiz_0 = -_xphm_phiz_msa(p, p.v_0, p.J_0_norm)-dphi
    p.zeta_0 = -_xphm_zeta_msa(p, p.v_0)-dzeta
    return p
end

_xphm_rotz(v, a) = [cos(a)*v[1]-sin(a)*v[2], sin(a)*v[1]+cos(a)*v[2], v[3]]
_xphm_roty(v, a) = [cos(a)*v[1]+sin(a)*v[3], v[2], -sin(a)*v[1]+cos(a)*v[3]]
_xphm_atan2tol(y, x) = abs(x) < 1e-15 && abs(y) < 1e-15 ? zero(x+y) : atan(y, x)

function _xphm_frame(eta, chi1, chi2, iota, phiRef, Mfref)
    delta = sqrt(max(0, 1-4eta))
    m1, m2 = (1+delta)/2, (1-delta)/2
    vref = cbrt(pi*Mfref)
    L2 = 3/2 + eta/6
    L3 = (-7*(chi1[3]+chi2[3]+delta*(chi1[3]-chi2[3])) +
          5eta*(chi1[3]+chi2[3]))/6
    L4 = (81+(-57+eta)*eta)/24
    L5 = (-1650*(chi1[3]+chi2[3]+delta*(chi1[3]-chi2[3])) +
          1336eta*(chi1[3]+chi2[3]) + 511delta*eta*(chi1[3]-chi2[3]) +
          28eta^2*(chi1[3]+chi2[3]))/600
    L6 = (10935+eta*(-62001+1674eta+7eta^2+2214pi^2))/1296
    LRef = eta/vref*(1+L2*vref^2+L3*vref^3+L4*vref^4+L5*vref^5+L6*vref^6)

    J = [m1^2*chi1[1]+m2^2*chi2[1],
         m1^2*chi1[2]+m2^2*chi2[2],
         m1^2*chi1[3]+m2^2*chi2[3]+LRef]
    Jnorm = _xphm_norm(J)
    thetaJ = Jnorm < 1e-10 ? zero(Jnorm) : acos(clamp(J[3]/Jnorm, -1, 1))
    phiJ = abs(J[1]) < 1e-15 && abs(J[2]) < 1e-15 ? zero(Jnorm) : atan(J[2], J[1])

    N = [sin(iota)*cos(pi/2-phiRef), sin(iota)*sin(pi/2-phiRef), cos(iota)]
    tmp = _xphm_roty(_xphm_rotz(N, -phiJ), -thetaJ)
    kappa = _xphm_atan2tol(tmp[2], tmp[1])
    alpha0 = pi-kappa                       # PhenomXP convention 1
    thetaJN = acos(clamp(dot(J,N)/Jnorm, -1, 1))

    X = [-cos(iota)*sin(phiRef), -cos(iota)*cos(phiRef), sin(iota)]
    Xj = _xphm_rotz(_xphm_roty(_xphm_rotz(X, -phiJ), -thetaJ), -kappa)
    P = [cos(thetaJN), zero(thetaJN), -sin(thetaJN)]
    Q = [zero(thetaJN), one(thetaJN), zero(thetaJN)]
    zeta_pol = atan(dot(Xj,Q), dot(Xj,P))
    epsilon0 = phiJ-pi
    return m1, m2, thetaJN, alpha0, epsilon0, zeta_pol
end

function _xphm_swsh(theta, ell, m)
    c, s = cos(theta), sin(theta)
    ch, sh = cos(theta/2), sin(theta/2)
    if ell == 2
        vals = (sqrt(5/(64pi))*(1-c)^2,
                sqrt(5/(16pi))*s*(1-c),
                sqrt(15/(32pi))*s^2,
                sqrt(5/(16pi))*s*(1+c),
                sqrt(5/(64pi))*(1+c)^2)
    elseif ell == 3
        vals = (sqrt(21/(2pi))*ch*sh^5,
                sqrt(7/(4pi))*(2+3c)*sh^4,
                sqrt(35/(2pi))*(s+4sin(2theta)-3sin(3theta))/32,
                sqrt(105/(2pi))*c*s^2/4,
                -sqrt(35/(2pi))*(s-4sin(2theta)-3sin(3theta))/32,
                sqrt(7/pi)*ch^4*(-2+3c)/2,
                -sqrt(21/(2pi))*ch^5*sh)
    elseif ell == 4
        vals = (3sqrt(7/pi)*ch^2*sh^6,
                3sqrt(7/(2pi))*ch*(1+2c)*sh^5,
                3*(9+14c+7cos(2theta))*sh^4/(4sqrt(pi)),
                3*(3s+2sin(2theta)+7sin(3theta)-7sin(4theta))/(32sqrt(2pi)),
                3sqrt(5/(2pi))*(5+7cos(2theta))*s^2/16,
                3*(3s-2sin(2theta)+7sin(3theta)+7sin(4theta))/(32sqrt(2pi)),
                3ch^4*(9-14c+7cos(2theta))/(4sqrt(pi)),
                -3sqrt(7/(2pi))*ch^5*(-1+2c)*sh,
                3sqrt(7/pi)*ch^6*sh^2)
    else
        throw(ArgumentError("IMRPhenomXPHM supports ell=2,3,4"))
    end
    return vals[m+ell+1]
end

function _xphm_wigner_arrays(ell, mp, cb, sb)
    if ell == 2 && mp == 2
        dp = [sb^4, 2cb*sb^3, sqrt(6)*sb^2*cb^2, 2cb^3*sb, cb^4]
        dm = [dp[5], -dp[4], dp[3], -dp[2], dp[1]]
    elseif ell == 2 && mp == 1
        dp = [2cb*sb^3, 3cb^2*sb^2-sb^4, sqrt(6)*(cb^3*sb-cb*sb^3),
              cb^2*(cb^2-3sb^2), -2cb^3*sb]
        dm = [-dp[5], dp[4], -dp[3], dp[2], -dp[1]]
    elseif ell == 3 && mp == 3
        dp = [sb^6, sqrt(6)*cb*sb^5, sqrt(15)*cb^2*sb^4, 2sqrt(5)*cb^3*sb^3,
              sqrt(15)*cb^4*sb^2, sqrt(6)*cb^5*sb, cb^6]
        dm = [dp[7], -dp[6], dp[5], -dp[4], dp[3], -dp[2], dp[1]]
    elseif ell == 3 && mp == 2
        dp = [sqrt(6)*cb*sb^5, sb^4*(5cb^2-sb^2),
              sqrt(10)*sb^3*(2cb^3-cb*sb^2), sqrt(30)*cb^2*(cb^2-sb^2)*sb^2,
              sqrt(10)*cb^3*(cb^2*sb-2sb^3), cb^4*(cb^2-5sb^2), -sqrt(6)*cb^5*sb]
        dm = [-dp[7], dp[6], -dp[5], dp[4], -dp[3], dp[2], -dp[1]]
    elseif ell == 4 && mp == 4
        dp = [sb^8, 2sqrt(2)*cb*sb^7, 2sqrt(7)*cb^2*sb^6, 2sqrt(14)*cb^3*sb^5,
              sqrt(70)*cb^4*sb^4, 2sqrt(14)*cb^5*sb^3, 2sqrt(7)*cb^6*sb^2,
              2sqrt(2)*cb^7*sb, cb^8]
        dm = [dp[9], -dp[8], dp[7], -dp[6], dp[5], -dp[4], dp[3], -dp[2], dp[1]]
    else
        throw(ArgumentError("unsupported XHM carrier mode ($ell,$mp)"))
    end
    return dp, dm
end

function _xphm_twist_mode(hlm, ell, mp, alpha, epsilon, cosbeta, thetaJN)
    cb = sqrt((1+cosbeta)/2)
    sb = sqrt((1-cosbeta)/2)
    dp, dm = _xphm_wigner_arrays(ell, mp, cb, sb)
    hpsum = zero(complex(hlm))
    hcsum = zero(complex(hlm))
    parity = iseven(ell) ? 1 : -1
    for m in -ell:ell
        Y = _xphm_swsh(thetaJN, ell, m)
        Aneg = cis(-m*alpha)*dm[m+ell+1]*Y
        Apos = cis( m*alpha)*dp[m+ell+1]*Y
        hpsum += Aneg + parity*Apos
        hcsum += im*(Aneg - parity*Apos)
    end
    fac = cis(-mp*epsilon)*hlm/2
    return fac*hpsum, fac*hcsum
end

function _xphm_setup(mc, eta, chi1, chi2, fRef, iota, phiRef, GMsun_over_c3)
    0 < eta <= 0.25 || throw(DomainError(eta, "eta must lie in (0, 0.25]"))
    M = mc/eta^(3/5)
    Mfref = M*GMsun_over_c3*fRef
    m1, m2, thetaJN, alpha0, epsilon0, zeta_pol =
        _xphm_frame(eta, chi1, chi2, iota, phiRef, Mfref)
    S1 = m1^2 .* collect(chi1)
    S2 = m2^2 .* collect(chi2)
    msa = _xphm_initialize_msa(eta, m1, m2, S1, S2, Mfref)
    phiref, zetaref, _ = _xphm_msa_angles(msa, msa.v_0)
    alpha_offset = phiref-alpha0
    epsilon_offset = zetaref-epsilon0
    return M, msa, thetaJN, zeta_pol, alpha_offset, epsilon_offset
end

function _xphm_aligned_final_spin(eta, chi1, chi2)
    eta2 = eta^2
    delta = sqrt(max(0, 1-4eta))
    m1, m2 = (1+delta)/2, (1-delta)/2
    totchi = (m1^2*chi1 + m2^2*chi2)/(m1^2+m2^2)
    dchi = chi1-chi2
    return (3.4641016151377544*eta + 20.0830030082033*eta2 - 12.333573402277912*eta^3)/(1+7.2388440419467335*eta) +
           (m1^2+m2^2)*totchi +
           ((-0.8561951310209386*eta-0.09939065676370885*eta2+1.668810429851045*eta^3)*totchi +
            (0.5881660363307388*eta-2.149269067519131*eta2+3.4768263932898678*eta^3)*totchi^2 +
            (0.142443244743048*eta-0.9598353840147513*eta2+1.9595643107593743*eta^3)*totchi^3) /
           (1+(-0.9142232693081653+2.3191363426522633*eta-9.710576749140989*eta^3)*totchi) +
           0.3223660562764661*dchi*delta*(1+9.332575956437443*eta)*eta2 -
           0.059808322561702126*dchi^2*eta^3 +
           2.3170397514509933*dchi*delta*(1-3.2624649875884852*eta)*eta^3*totchi
end

function _xphm_precessing_final_spin(p, chi1z, chi2z)
    af_parallel = _xphm_aligned_final_spin(p.eta, chi1z, chi2z)
    Lfinal = af_parallel-p.S1_0[3]-p.S2_0[3]
    magnitude = sqrt(p.SAv2+Lfinal^2+2Lfinal*(p.S1L_pav+p.S2L_pav))
    # LAL's default transition-precession method copies the sign of the
    # aligned remnant and caps unphysical fit extrapolations at unit spin.
    return copysign(min(magnitude, one(magnitude)), af_parallel)
end

"""
    hphc(PhenomXPHM(), f, mc, eta,
         chi1x, chi1y, chi1z, chi2x, chi2y, chi2z, dL, iota; kwargs...)

Frequency-domain IMRPhenomXPHM polarizations. Masses are in solar masses,
distance is in Gpc, frequencies are in Hz, and the Cartesian spins are
specified in the source frame where the reference orbital angular momentum is
the positive z axis. The implementation follows the LAL default MSA version
223 and twists the co-precessing `(2,2)`, `(2,1)`, `(3,3)`, `(3,2)`, and `(4,4)`
IMRPhenomXHM modes.
"""
function hphc(model::PhenomXPHM, f::AbstractVector, mc, eta,
              chi1x, chi1y, chi1z, chi2x, chi2y, chi2z, dL, iota;
              phiRef=0.0, fRef=minimum(f), prec_version=300,
              fcutPar=0.3, GMsun_over_c3=_XPHM_MTSUN_SI,
              GMsun_over_c2_Gpc=_XPHM_MRSUN_GPC)
    prec_version in (223, 300) ||
        throw(ArgumentError("only the LAL default MSA precession version 223 (or its public alias 300) is implemented"))
    fRef > 0 || throw(DomainError(fRef, "fRef must be positive"))
    chi1 = [chi1x, chi1y, chi1z]
    chi2 = [chi2x, chi2y, chi2z]
    M, msa, thetaJN, zeta_pol, alpha_offset, epsilon_offset =
        _xphm_setup(mc, eta, chi1, chi2, fRef, iota, phiRef, GMsun_over_c3)
    afinal_prec = _xphm_precessing_final_spin(msa, chi1z, chi2z)

    carriers = hphc(PhenomXHM(), f, mc, eta, chi1z, chi2z, dL, zero(iota);
                    return_modes=true, final_spin_override=afinal_prec, fRef=fRef, fcutPar=fcutPar,
                    GMsun_over_c3=GMsun_over_c3,
                    GMsun_over_c2_Gpc=GMsun_over_c2_Gpc)
    hp = zeros(ComplexF64, length(f))
    hc = zeros(ComplexF64, length(f))
    active = ((2,2), (2,1), (3,3), (3,2), (4,4))
    for (ell, mp) in active
        hlm = carriers[(ell,-mp)]
        for i in eachindex(f)
            v = cbrt(pi*(M*GMsun_over_c3*f[i])*(2/mp))
            phiz, zeta, cosbeta = _xphm_msa_angles(msa, v)
            alpha = phiz-alpha_offset
            epsilon = zeta-epsilon_offset
            dhp, dhc = _xphm_twist_mode(hlm[i], ell, mp, alpha, epsilon, cosbeta, thetaJN)
            hp[i] += dhp
            hc[i] += dhc
        end
    end

    cpol, spol = cos(2zeta_pol), sin(2zeta_pol)
    hp0 = copy(hp)
    hp .= cpol.*hp0 .+ spol.*hc
    hc .= cpol.*hc .- spol.*hp0
    return hp, hc
end

function hphc(model::PhenomXPHM, f::AbstractVector, mc, eta,
              chi1::Union{Tuple,AbstractVector}, chi2::Union{Tuple,AbstractVector},
              dL, iota; kwargs...)
    length(chi1) == 3 && length(chi2) == 3 || throw(ArgumentError("spin vectors must have three components"))
    return hphc(model, f, mc, eta, chi1[1], chi1[2], chi1[3],
                chi2[1], chi2[2], chi2[3], dL, iota; kwargs...)
end

function Pol(model::PhenomXPHM, f::AbstractVector, mc, eta,
             chi1x, chi1y, chi1z, chi2x, chi2y, chi2z, dL, iota,
             Lambda1=0.0, Lambda2=0.0; kwargs...)
    return collect(hphc(model, f, mc, eta, chi1x, chi1y, chi1z,
                        chi2x, chi2y, chi2z, dL, iota; kwargs...))
end

function PolAbs(model::PhenomXPHM, f::AbstractVector, mc, eta,
                chi1x, chi1y, chi1z, chi2x, chi2y, chi2z, dL, iota,
                Lambda1=0.0, Lambda2=0.0; kwargs...)
    hp, hc = hphc(model, f, mc, eta, chi1x, chi1y, chi1z,
                  chi2x, chi2y, chi2z, dL, iota; kwargs...)
    return [abs.(hp), abs.(hc)]
end

function Phi(model::PhenomXPHM, f, mc, eta,
             chi1x, chi1y, chi1z, chi2x, chi2y, chi2z; kwargs...)
    return zero.(f)
end
